SELECT 
    R.ID AS ID_RESERVA,
    R.DATA,
    R.H_INICIO,
    R.H_FIM,
    RR.QUANTIDADE,
    CASE 
        WHEN RC.TIPO = 'Comida' THEN C.DESIGNACAO
        WHEN RC.TIPO = 'Bebida' THEN B.DESIGNACAO
        WHEN RC.TIPO = 'Equipamento' THEN E.DESIGNACAO
    END AS RECURSO
FROM 
    RESERVAS R
JOIN 
    RESERVAS_RECURSOS RR ON R.ID = RR.ID_RESERVA
JOIN 
    RECURSOS RC ON RR.ID_RECURSO = RC.ID
LEFT JOIN 
    COMIDA C ON RC.TIPO = 'Comida' AND RC.ID_COMIDA = C.ID
LEFT JOIN 
    BEBIDA B ON RC.TIPO = 'Bebida' AND RC.ID_BEBIDA = B.ID
LEFT JOIN 
    EQUIPAMENTOS E ON RC.TIPO = 'Equipamento' AND RC.ID_EQUIPAMENTO = E.ID;


SELECT 
    S.NOME AS SALA,
    SR.QUANTIDADE,
    CASE 
        WHEN RC.TIPO = 'Comida' THEN C.DESIGNACAO
        WHEN RC.TIPO = 'Bebida' THEN B.DESIGNACAO
        WHEN RC.TIPO = 'Equipamento' THEN E.DESIGNACAO
    END AS RECURSO
FROM 
    SALAS S
JOIN 
    SALAS_RECURSOS SR ON S.ID = SR.ID_SALA
JOIN 
    RECURSOS RC ON SR.ID_RECURSO = RC.ID
LEFT JOIN 
    COMIDA C ON RC.TIPO = 'Comida' AND RC.ID_COMIDA = C.ID
LEFT JOIN 
    BEBIDA B ON RC.TIPO = 'Bebida' AND RC.ID_BEBIDA = B.ID
LEFT JOIN 
    EQUIPAMENTOS E ON RC.TIPO = 'Equipamento' AND RC.ID_EQUIPAMENTO = E.ID;
	